name: Flutter Web CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'  # Specify your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Clean the project
        run: flutter clean

      - name: Build for web
        run: flutter build web --release
